### ISSUE TITLE
[bug] Android images detect Linux on default profile

### ISSUE THREAD

**Issue by uilianries** [conan-io/conan-docker-tools#126]
### Environment Details
* Conan Docker Tools image: **conanio/xxx-android**
* Operating System: **Linux**
* Operation System Version: **Ubuntu 16.04**
* Python version (If you are building some image): **python 3.7.0**

### Steps to reproduce (Include if Applicable)

    docker run --rm -ti conanio/gcc8-android
    conan profile show default

/cc @ericLemanissier

**Comment by ericLemanissier** [comment]
On my end, `docker run --rm -ti conanio/android-clang8 conan profile show default` shows the following:
```
[settings]
os=Android
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=clang
compiler.version=8
compiler.libcxx=libc++
build_type=Release
os.api_level=21
[options]
[build_requires]
[env]
```
which is ok (os=Android)
The problem happens on CI, when running conan-package tools (full log https://dev.azure.com/bincrafters/packages/_build/results?buildId=246):
```
>> sudo -E docker run --rm -v "/home/vsts/work/1/s:/home/conan/project" -e CONAN_CLANG_VERSIONS="8" -e CONAN_DOCKER_IMAGE="conanio/android-clang8" -e CONAN_ARCHS="x86_64" -e CONAN_LOGIN_USERNAME="***" -e CONAN_UPLOAD_ONLY_WHEN_STABLE="1" -e CONAN_PASSWORD="***" -e CONAN_DOCKER_32_IMAGES="True" -e CONAN_CHANNEL="testing" -e CONAN_UPLOAD="https://api.bintray.com/conan/bincrafters/public-conan@True@upload_repo" -e CONAN_REMOTES="https://api.bintray.com/conan/bincrafters/public-conan@True@remote0" -e CONAN_REFERENCE="qt/5.13.0-beta1@bincrafters/testing" -e CPT_PROFILE="@@include(default)@@@@[settings]@@arch=x86_64@@build_type=Release@@compiler=clang@@compiler.version=8@@[options]@@qt:shared=True@@[env]@@@@[build_requires]@@@@" -e CONAN_USERNAME="bincrafters" -e CONAN_TEMP_TEST_FOLDER="1" -e CPT_UPLOAD_RETRY="3" -e CPT_BUILD_POLICY="missing" -e CPT_CONANFILE="conanfile.py"   conanio/android-clang8 /bin/sh -c " cd project &&  run_create_in_docker "

____________________________________________________________________________________________________
WARN: Running a full revision metadata migration
CC and CXX: /android-ndk-r19c/toolchains/llvm/prebuilt/linux-x86_64/bin/x86_64-linux-android21-clang, /android-ndk-r19c/toolchains/llvm/prebuilt/linux-x86_64/bin/x86_64-linux-android21-clang++ 
Found clang 8.0
clang>=8, using the major as version
Profile created with detected settings: /home/conan/.conan/profiles/default

****************************************************************************************************
+--------------------+
| Profile            |
|--------------------|
| include(default)   |
|                    |
| [settings]         |
| arch=x86_64        |
| build_type=Release |
| compiler=clang     |
| compiler.version=8 |
| [options]          |
| qt:shared=True     |
| [env]              |
|                    |
| [build_requires]   |
+--------------------+

[conan_create]

 >> Calling 'conan create'
+-----------------+------------------------------------------------------+
| Configuration   | value                                                |
|-----------------+------------------------------------------------------|
| name            | qt                                                   |
| version         | 5.13.0-beta1                                         |
| user            | bincrafters                                          |
| channel         | testing                                              |
| build_modes     | ['missing']                                          |
| profile_name    | /tmp/tmpqu9hc9jbconan_package_tools_profiles/profile |
+-----------------+------------------------------------------------------+
Exporting package recipe
Linter warnings
    WARN: Linter. Line 26: Method has no argument
    WARN: Linter. Line 536: Unused variable 'dirnames'
qt/5.13.0-beta1@bincrafters/testing exports: Copied 1 '.md' file: LICENSE.md
qt/5.13.0-beta1@bincrafters/testing exports: Copied 1 '.conf' file: qtmodules.conf
qt/5.13.0-beta1@bincrafters/testing: A new conanfile.py version was exported
qt/5.13.0-beta1@bincrafters/testing: Folder: /home/conan/.conan/data/qt/5.13.0-beta1/bincrafters/testing/export
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=clang
compiler.libcxx=libstdc++
compiler.version=8
os=Linux
os_build=Linux
[options]
qt:shared=True
[build_requires]
[env]
```
Here we get `os=Linux` which is wrong

**Comment by ericLemanissier** [comment]
It looks like the command `run_create_in_docker` is overwriting the existing default profile. I ran the following command `conan profile show default && cd project &&  run_create_in_docker || conan profile show default` in the docker container , it starts with proper profile:
```
Configuration for profile default:

[settings]
os=Android
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=clang
compiler.version=8
compiler.libcxx=libc++
build_type=Release
os.api_level=21
[options]
[build_requires]
[env]
```
But after `run_create_in_docker` I get 
```
Configuration for profile default:

[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=clang
compiler.version=8
compiler.libcxx=libstdc++
build_type=Release
[options]
[build_requires]
[env]
```
Which is not correct.

This issue should probably moved to https://github.com/conan-io/conan-package-tools or https://github.com/conan-io/conan

The full command is ` sudo -E docker run --rm -v "/home/vsts/work/1/s:/home/conan/project" -e CONAN_CLANG_VERSIONS="8" -e CONAN_DOCKER_IMAGE="conanio/android-clang8" -e CONAN_ARCHS="x86_64" -e CONAN_LOGIN_USERNAME="***" -e CONAN_UPLOAD_ONLY_WHEN_STABLE="1" -e CONAN_PASSWORD="***" -e CONAN_DOCKER_32_IMAGES="True" -e CONAN_CHANNEL="testing" -e CONAN_UPLOAD="https://api.bintray.com/conan/bincrafters/public-conan@True@upload_repo" -e CONAN_REMOTES="https://api.bintray.com/conan/bincrafters/public-conan@True@remote0" -e CONAN_REFERENCE="qt/5.13.0-beta1@bincrafters/testing" -e CPT_PROFILE="@@include(default)@@@@[settings]@@arch=x86_64@@build_type=Release@@compiler=clang@@compiler.version=8@@[options]@@qt:shared=True@@[env]@@@@[build_requires]@@@@" -e CONAN_USERNAME="bincrafters" -e CONAN_TEMP_TEST_FOLDER="1" -e CPT_UPLOAD_RETRY="3" -e CPT_BUILD_POLICY="missing" -e CPT_CONANFILE="conanfile.py"   conanio/android-clang8 /bin/sh -c " conan profile show default && cd project &&  run_create_in_docker || conan profile show default"`
and the full ouput is
```
WARN: Running a full revision metadata migration
Configuration for profile default:

[settings]
os=Android
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=clang
compiler.version=8
compiler.libcxx=libc++
build_type=Release
os.api_level=21
[options]
[build_requires]
[env]
CC and CXX: /android-ndk-r19c/toolchains/llvm/prebuilt/linux-x86_64/bin/x86_64-linux-android21-clang, /android-ndk-r19c/toolchains/llvm/prebuilt/linux-x86_64/bin/x86_64-linux-android21-clang++
Found clang 8.0
clang>=8, using the major as version
Profile created with detected settings: /home/conan/.conan/profiles/default

****************************************************************************************************
+--------------------+
| Profile            |
|--------------------|
| include(default)   |
|                    |
| [settings]         |
| arch=x86_64        |
| build_type=Release |
| compiler=clang     |
| compiler.version=8 |
| [options]          |
| qt:shared=True     |
| [env]              |
|                    |
| [build_requires]   |
+--------------------+

[conan_create]

 >> Calling 'conan create'
+-----------------+------------------------------------------------------+
| Configuration   | value                                                |
|-----------------+------------------------------------------------------|
| name            | qt                                                   |
| version         | 5.13.0-beta1                                         |
| user            | bincrafters                                          |
| channel         | testing                                              |
| build_modes     | ['missing']                                          |
| profile_name    | /tmp/tmp_rogzrvwconan_package_tools_profiles/profile |
+-----------------+------------------------------------------------------+
Traceback (most recent call last):
  File "/opt/pyenv/versions/3.7.1/bin/run_create_in_docker", line 11, in <module>
    load_entry_point('conan-package-tools==0.25.1', 'console_scripts', 'run_create_in_docker')()
  File "/opt/pyenv/versions/3.7.1/lib/python3.7/site-packages/cpt/run_in_docker.py", line 50, in run
    runner.run()
  File "/opt/pyenv/versions/3.7.1/lib/python3.7/site-packages/cpt/runner.py", line 108, in run
    test_folder=self._test_folder)
  File "/opt/pyenv/versions/3.7.1/lib/python3.7/site-packages/conans/client/conan_api.py", line 93, in wrapper
    return f(*args, **kwargs)
  File "/opt/pyenv/versions/3.7.1/lib/python3.7/site-packages/conans/client/conan_api.py", line 357, in create
    conanfile_path = _get_conanfile_path(conanfile_path, cwd, py=True)
  File "/opt/pyenv/versions/3.7.1/lib/python3.7/site-packages/conans/client/conan_api.py", line 146, in _get_conanfile_path
    raise ConanException("Conanfile not found at %s" % " or ".join(candidate_paths))
conans.errors.ConanException: Conanfile not found at /home/conan/project/conanfile.py
Configuration for profile default:

[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=clang
compiler.version=8
compiler.libcxx=libstdc++
build_type=Release
[options]
[build_requires]
[env]
```

**Comment by uilianries** [comment]
Seems like the CPT_PROFILE is wrong:

`-e CPT_PROFILE="@@include(default)@@@@[settings]@@arch=x86_64@@build_type=Release@@compiler=clang@@compiler.version=8@@[options]@@qt:shared=True@@[env]@@@@[build_requires]@@@@"`

It's a case for Conan Package Tools.

**Comment by ericLemanissier** [comment]
This part is actually correct. The wrong part is the content of the default profile, which is erased by conan package tools and replaced with and auto-detected profile

**Comment by uilianries** [comment]
Hi @ericLemanissier!

CPT 0.26.0 will be released soon with this fix!

**Comment by lasote** [comment]
Released
