### ISSUE TITLE
Conan Package Tools unable to run

### ISSUE THREAD

**Issue by UnderSampled** [conan-io/conan-docker-tools#159]
### Description of Problem, Request, or Question

I cannot seem to use Conan Package Tools in the GCC containers

### Environment Details
* Conan Docker Tools image: **conanio/gcc7:1.13.1**
* Operating System: **Windows**
* Operation System Version: **Windows 10 1909 running Docker for Windows Desktop**

### Steps to reproduce (Include if Applicable)
1. Run a GCC container (I've tried with `gcc7` and `gcc8`: `docker run -it --rm conanio/gcc7 bash`
2. Run python: `python`
3. Import ConanMultiPackager: `from cpt.packager import ConanMultiPackager`

This returns the following error stack:
```
>>> from cpt.packager import ConanMultiPackager
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/pyenv/versions/3.7.1/lib/python3.7/site-packages/cpt/packager.py", line 8, in <module>
    from conans import tools
  File "/opt/pyenv/versions/3.7.1/lib/python3.7/site-packages/conans/__init__.py", line 3, in <module>
    from conans.client.build.autotools_environment import AutoToolsBuildEnvironment
  File "/opt/pyenv/versions/3.7.1/lib/python3.7/site-packages/conans/client/build/autotools_environment.py", line 6, in <module>
    from conans.client.build.compiler_flags import (architecture_flag, build_type_define,
  File "/opt/pyenv/versions/3.7.1/lib/python3.7/site-packages/conans/client/build/compiler_flags.py", line 12, in <module>
    from conans.client.tools.oss import cpu_count
  File "/opt/pyenv/versions/3.7.1/lib/python3.7/site-packages/conans/client/tools/__init__.py", line 4, in <module>
    from .apple import *
  File "/opt/pyenv/versions/3.7.1/lib/python3.7/site-packages/conans/client/tools/apple.py", line 5, in <module>
    from conans.client.tools.oss import check_output
  File "/opt/pyenv/versions/3.7.1/lib/python3.7/site-packages/conans/client/tools/oss.py", line 6, in <module>
    import tempfile
  File "/opt/pyenv/versions/3.7.1/lib/python3.7/tempfile.py", line 43, in <module>
    import shutil as _shutil
  File "/opt/pyenv/versions/3.7.1/lib/python3.7/shutil.py", line 15, in <module>
    import zlib
  File "/home/conan/conan-3rd-party/zlib.py", line 1, in <module>
    from conans import ConanFile, CMake, tools
  File "/opt/pyenv/versions/3.7.1/lib/python3.7/site-packages/conans/tools.py", line 13, in <module>
    import requests
  File "/opt/pyenv/versions/3.7.1/lib/python3.7/site-packages/requests/__init__.py", line 43, in <module>
    import urllib3
  File "/opt/pyenv/versions/3.7.1/lib/python3.7/site-packages/urllib3/__init__.py", line 7, in <module>
    from .connectionpool import HTTPConnectionPool, HTTPSConnectionPool, connection_from_url
  File "/opt/pyenv/versions/3.7.1/lib/python3.7/site-packages/urllib3/connectionpool.py", line 39, in <module>
    from .response import HTTPResponse
  File "/opt/pyenv/versions/3.7.1/lib/python3.7/site-packages/urllib3/response.py", line 155, in <module>
    class HTTPResponse(io.IOBase):
  File "/opt/pyenv/versions/3.7.1/lib/python3.7/site-packages/urllib3/response.py", line 375, in HTTPResponse
    DECODER_ERROR_CLASSES = (IOError, zlib.error)
AttributeError: module 'zlib' has no attribute 'error'
```

**Comment by uilianries** [comment]
Hi @UnderSampled !

The revision 1.13.1 is pretty old, could you please update your Docker image?

    docker install conanio/gcc7

**Comment by UnderSampled** [comment]
I was using gcc7:latest. I am not quite sure the actual version, but I downloaded it today. 1.13.1 was the template for the bug report.

**Comment by uilianries** [comment]
Understood. I'll need to install Docker in my Windows partition to reproduce your error, but I can say that is working on Linux, otherwise Bincrafters CI jobs should be broken. Thanks for reporting

**Comment by ericLemanissier** [comment]
Are linux docker images supposed to work in docker for windows ?

**Comment by uilianries** [comment]
@ericLemanissier Yes, Windows gives support for Linux Docker Images since 2 years ago I think. The problem is run Docker nicely on Windows :stuck_out_tongue_closed_eyes:

**Comment by ericLemanissier** [comment]
I thought linux and windows were using different docker images : https://hub.docker.com/_/hello-world?tab=tags has different images for linux and windows, whereas https://hub.docker.com/r/conanio/gcc7/tags has only linux images

**Comment by Croydon** [comment]
No, Docker images are the same regardless the host OS. I guess that the simply uploaded this Hello World example in different guest OS variants to demonstrate the flexibility of Docker

On Windows versions without the Windows Subsystem for Linux (WSL) it will use a Linux Virtual Machine in the background to run a Docker image with a Linux guest.
On Windows versions with WSL it will use just this.
WSL 1 is comparable to what WINE does on Linux for Windows applications.
WSL 2 will run an actual Linux kernel in Windows.

But anyway, since this is about a Python error and not some crazy low-level stuff happening, I'm pretty sure that it has nothing to do with any of this

**Comment by Croydon** [comment]
That being said I can't reproduce your problem

```
PS C:\Users\user> docker run -it --rm conanio/gcc7 bash
Unable to find image 'conanio/gcc7:latest' locally
latest: Pulling from conanio/gcc7
4ccdce43d1e0: Pull complete
c95f13c88d92: Pull complete
82656eee95ad: Pull complete
78ff727be57a: Pull complete
448bb314afa5: Pull complete
c10118153369: Pull complete
8b6b8e0753d9: Pull complete
ddbc0eb7d4a8: Pull complete
Digest: sha256:b44206ae84cb83d15ab0c12a52c9724abfa9a382f82a4c2a9ddcf9706963a26b
Status: Downloaded newer image for conanio/gcc7:latest
To run a command as administrator (user "root"), use "sudo <command>".
See "man sudo_root" for details.

conan@8c7bea6d2a13:~$ python --version
Python 3.7.1
conan@8c7bea6d2a13:~$ python
Python 3.7.1 (default, Dec 10 2019, 11:40:59)
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from cpt.packager import ConanMultiPackager
```

**Comment by uilianries** [comment]
THanks @Croydon ! On the last time that I tried to install Docker on my Windows machine I gave up.

**Comment by UnderSampled** [comment]
So, the answer to all of this turned out to be that I had a 'zlib.py' file (I am building recipes of multiple libraries) in the same directory as where I ran my build.py. Python then used that instead of the actual zlib.
