### ISSUE TITLE
cmake_installer build fails on gcc7-centos7-x86

### ISSUE THREAD

**Issue by dheater** [conan-io/conan-docker-tools#166]
### Description of Problem, Request, or Question

Fail to build `cmake_installer/3.13.0@conan/stable -s arch_build=x86 -s os_build=Linux --build` on `gcc7-centos-x86`

### Environment Details
* Conan Docker Tools image: **gcc7-centos6-x86 from Github**
* Operating System: **Linux**
* Operation System Version: **Centos 7**
* Python version (If you are building some image): **python 3.6.9**

### Steps to reproduce (Include if Applicable)

Build `gcc7-centos6-x86` from `Dockerfile` in github, at commit 30e5716f00fe80cf6b43dfd75857c104dab0694b.

Run:
```
docker exec gcc7-centos6-x86 conan install cmake_installer/3.13.0@conan/stable -s arch_build=x86 -s os_build=Linux --build
```
### Build logs (Include if Available)

Partial log from CI job (https://dev.azure.com/conanio/conan-docker-tools/_build/results?buildId=303&view=logs&j=55a3690d-934c-56b6-d406-15fe3f8f457f&t=fe69285c-78b7-5d58-00f7-0d94e41e53f1):
```
-- Check size of unsigned short
-- Check size of unsigned short - failed
-- Check size of unsigned int
-- Check size of unsigned int - failed
-- Check size of unsigned long
-- Check size of unsigned long - failed
CMake Error at /usr/local/share/cmake-3.15/Modules/TestBigEndian.cmake:50 (message):
  no suitable type found
Call Stack (most recent call first):
  Utilities/cmexpat/ConfigureChecks.cmake:27 (test_big_endian)
  Utilities/cmexpat/CMakeLists.txt:9 (include)


-- Configuring incomplete, errors occurred!
See also "/home/conan/.conan/data/cmake_installer/3.13.0/conan/stable/build/445cf80f611c1d1eda08bde2ebc5066218ca9701/CMakeFiles/CMakeOutput.log".
See also "/home/conan/.conan/data/cmake_installer/3.13.0/conan/stable/build/445cf80f611c1d1eda08bde2ebc5066218ca9701/CMakeFiles/CMakeError.log".
cmake_installer/3.13.0@conan/stable: 
cmake_installer/3.13.0@conan/stable: ERROR: Package '445cf80f611c1d1eda08bde2ebc5066218ca9701' build failed
cmake_installer/3.13.0@conan/stable: WARN: Build folder /home/conan/.conan/data/cmake_installer/3.13.0/conan/stable/build/445cf80f611c1d1eda08bde2ebc5066218ca9701
ERROR: cmake_installer/3.13.0@conan/stable: Error in build() method, line 127
	cmake = self._configure_cmake()
while calling '_configure_cmake', line 116
	cmake.configure(source_dir=self._source_subfolder)
	ConanException: Error 1 while executing cd '/home/conan/.conan/data/cmake_installer/3.13.0/conan/stable/build/445cf80f611c1d1eda08bde2ebc5066218ca9701' && cmake -G "Unix Makefiles" -DCONAN_IN_LOCAL_CACHE="ON" -DCONAN_COMPILER="gcc" -DCONAN_COMPILER_VERSION="7" -DCONAN_CXX_FLAGS="-m32" -DCONAN_SHARED_LINKER_FLAGS="-m32" -DCONAN_C_FLAGS="-m32" -DCONAN_LIBCXX="libstdc++" -DCMAKE_INSTALL_PREFIX="/home/conan/.conan/data/cmake_installer/3.13.0/conan/stable/package/445cf80f611c1d1eda08bde2ebc5066218ca9701" -DCMAKE_INSTALL_BINDIR="bin" -DCMAKE_INSTALL_SBINDIR="bin" -DCMAKE_INSTALL_LIBEXECDIR="bin" -DCMAKE_INSTALL_LIBDIR="lib" -DCMAKE_INSTALL_INCLUDEDIR="include" -DCMAKE_INSTALL_OLDINCLUDEDIR="include" -DCMAKE_INSTALL_DATAROOTDIR="share" -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY="ON" -DCONAN_EXPORTED="1" -DCMAKE_BOOTSTRAP="False" -DOPENSSL_USE_STATIC_LIBS="True" -DCMAKE_EXE_LINKER_FLAGS="-lz" -Wno-dev 'source_subfolder'
gcc7-centos6-x86

 >> CI detected: Azure Pipelines
Traceback (most recent call last):
  File "build.py", line 418, in <module>
    conan_docker_tools.run()
  File "build.py", line 412, in run
    self.process_distro_images()
  File "build.py", line 404, in process_distro_images
    self.test(arch, compiler.name, version, distro)
  File "build.py", line 183, in test
    self.test_linux(arch, compiler_name, compiler_version, distro)
  File "build.py", line 286, in test_linux
    shell=True)
  File "/opt/hostedtoolcache/Python/3.6.9/x64/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'docker exec gcc7-centos6-x86 conan install cmake_installer/3.13.0@conan/stable -s arch_build=x86 -s os_build=Linux --build' returned non-zero exit status 1.
##[error]Bash exited with code '1'.
Finishing: CmdLine
```

**Comment by dheater** [comment]
Fail to reproduce after reverting change to Dockerfile.
