### ISSUE TITLE
nodejs installation fails on latest gcc8/gcc9 images

### ISSUE THREAD

**Issue by GirtsR** [conan-io/conan-docker-tools#364]
### Environment Details
* Conan Docker Tools image: **conanio/gcc9:1.44.1**, **conanio/gcc9:1.43.3**, **conanio/gcc8:1.44.1**, **conanio/gcc8:1.43.3** 
* Operating System: **Linux**
* Operation System Version: **Ubuntu 20.04**
* Python version (If you are building some image): **python 3.7.5**

### Steps to reproduce (Include if Applicable)

- Run the latest conanio/gcc9 (or conanio/gcc8) image and attempt to install nodesource binaries:
```
curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash
```

### Build logs (Include if Available)

```
conan@d2c9b94babef:~$ curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash

## Installing the NodeSource Node.js 14.x repo...


## Populating apt-get cache...

+ apt-get update
Get:1 http://ppa.launchpad.net/git-core/ppa/ubuntu eoan InRelease [20.7 kB]
Get:2 http://old-releases.ubuntu.com/ubuntu eoan InRelease [255 kB]
Get:3 http://ppa.launchpad.net/git-core/ppa/ubuntu eoan/main i386 Packages [3181 B]
Get:4 http://ppa.launchpad.net/git-core/ppa/ubuntu eoan/main amd64 Packages [3185 B]
Get:5 http://old-releases.ubuntu.com/ubuntu eoan-updates InRelease [97.5 kB]
Get:6 http://old-releases.ubuntu.com/ubuntu eoan-backports InRelease [88.8 kB]
Get:7 http://old-releases.ubuntu.com/ubuntu eoan-security InRelease [97.5 kB]
Get:8 http://old-releases.ubuntu.com/ubuntu eoan/universe Sources [12.3 MB]
Get:9 http://old-releases.ubuntu.com/ubuntu eoan/restricted amd64 Packages [22.7 kB]
Get:10 http://old-releases.ubuntu.com/ubuntu eoan/multiverse i386 Packages [173 kB]
Get:11 http://old-releases.ubuntu.com/ubuntu eoan/restricted i386 Packages [14.4 kB]
Get:12 http://old-releases.ubuntu.com/ubuntu eoan/universe i386 Packages [11.5 MB]
Get:13 http://old-releases.ubuntu.com/ubuntu eoan/main i386 Packages [1254 kB]
Get:14 http://old-releases.ubuntu.com/ubuntu eoan/main amd64 Packages [1277 kB]
Get:15 http://old-releases.ubuntu.com/ubuntu eoan/multiverse amd64 Packages [188 kB]
Get:16 http://old-releases.ubuntu.com/ubuntu eoan/universe amd64 Packages [11.6 MB]
Get:17 http://old-releases.ubuntu.com/ubuntu eoan-updates/universe Sources [54.7 kB]
Get:18 http://old-releases.ubuntu.com/ubuntu eoan-updates/restricted amd64 Packages [56.6 kB]
Get:19 http://old-releases.ubuntu.com/ubuntu eoan-updates/multiverse amd64 Packages [1074 B]
Get:20 http://old-releases.ubuntu.com/ubuntu eoan-updates/restricted i386 Packages [7958 B]
Get:21 http://old-releases.ubuntu.com/ubuntu eoan-updates/universe amd64 Packages [283 kB]
Get:22 http://old-releases.ubuntu.com/ubuntu eoan-updates/multiverse i386 Packages [1258 B]
Get:23 http://old-releases.ubuntu.com/ubuntu eoan-updates/universe i386 Packages [272 kB]
Get:24 http://old-releases.ubuntu.com/ubuntu eoan-updates/main amd64 Packages [431 kB]
Get:25 http://old-releases.ubuntu.com/ubuntu eoan-updates/main i386 Packages [296 kB]
Get:26 http://old-releases.ubuntu.com/ubuntu eoan-backports/main amd64 Packages [669 B]
Get:27 http://old-releases.ubuntu.com/ubuntu eoan-backports/main i386 Packages [669 B]
Get:28 http://old-releases.ubuntu.com/ubuntu eoan-backports/universe amd64 Packages [4108 B]
Get:29 http://old-releases.ubuntu.com/ubuntu eoan-backports/universe i386 Packages [4106 B]
Get:30 http://old-releases.ubuntu.com/ubuntu eoan-security/universe Sources [33.0 kB]
Get:31 http://old-releases.ubuntu.com/ubuntu eoan-security/universe amd64 Packages [221 kB]
Get:32 http://old-releases.ubuntu.com/ubuntu eoan-security/main i386 Packages [195 kB]
Get:33 http://old-releases.ubuntu.com/ubuntu eoan-security/restricted amd64 Packages [56.6 kB]
Get:34 http://old-releases.ubuntu.com/ubuntu eoan-security/main amd64 Packages [328 kB]
Get:35 http://old-releases.ubuntu.com/ubuntu eoan-security/multiverse amd64 Packages [1074 B]
Get:36 http://old-releases.ubuntu.com/ubuntu eoan-security/multiverse i386 Packages [1258 B]
Get:37 http://old-releases.ubuntu.com/ubuntu eoan-security/restricted i386 Packages [7958 B]
Get:38 http://old-releases.ubuntu.com/ubuntu eoan-security/universe i386 Packages [210 kB]
Fetched 41.3 MB in 7s (6055 kB/s)
Reading package lists... Done
Traceback (most recent call last):
  File "/usr/bin/lsb_release", line 25, in <module>
    import lsb_release
ModuleNotFoundError: No module named 'lsb_release'
Traceback (most recent call last):
  File "/usr/bin/lsb_release", line 25, in <module>
    import lsb_release
ModuleNotFoundError: No module named 'lsb_release'

## Confirming "" is supported...

+ curl -sLf -o /dev/null 'https://deb.nodesource.com/node_14.x/dists//Release'

## Your distribution, identified as "", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support
```

### Additional note

If `conanio/gcc9:1.44.0` or `conanio/gcc8:1.44.0` images are used (or older ones), the installation completes successfully:

```
conan@671026ca4a97:~$ curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash

## Installing the NodeSource Node.js 14.x repo...


## Populating apt-get cache...

+ apt-get update
Get:1 http://old-releases.ubuntu.com/ubuntu eoan InRelease [255 kB]
Get:2 http://old-releases.ubuntu.com/ubuntu eoan-updates InRelease [97.5 kB]
Get:3 http://old-releases.ubuntu.com/ubuntu eoan-backports InRelease [88.8 kB]
Get:4 http://old-releases.ubuntu.com/ubuntu eoan-security InRelease [97.5 kB]
Get:5 http://old-releases.ubuntu.com/ubuntu eoan/universe Sources [12.3 MB]
Get:6 http://old-releases.ubuntu.com/ubuntu eoan/universe amd64 Packages [11.6 MB]
Get:7 http://old-releases.ubuntu.com/ubuntu eoan/main amd64 Packages [1277 kB]
Get:8 http://old-releases.ubuntu.com/ubuntu eoan/main i386 Packages [1254 kB]
Get:9 http://old-releases.ubuntu.com/ubuntu eoan/restricted amd64 Packages [22.7 kB]
Get:10 http://old-releases.ubuntu.com/ubuntu eoan/multiverse amd64 Packages [188 kB]
Get:11 http://old-releases.ubuntu.com/ubuntu eoan/restricted i386 Packages [14.4 kB]
Get:12 http://old-releases.ubuntu.com/ubuntu eoan/multiverse i386 Packages [173 kB]
Get:13 http://old-releases.ubuntu.com/ubuntu eoan/universe i386 Packages [11.5 MB]
Get:14 http://old-releases.ubuntu.com/ubuntu eoan-updates/universe Sources [54.7 kB]
Get:15 http://old-releases.ubuntu.com/ubuntu eoan-updates/multiverse amd64 Packages [1074 B]
Get:16 http://old-releases.ubuntu.com/ubuntu eoan-updates/restricted i386 Packages [7958 B]
Get:17 http://old-releases.ubuntu.com/ubuntu eoan-updates/universe i386 Packages [272 kB]
Get:18 http://old-releases.ubuntu.com/ubuntu eoan-updates/main amd64 Packages [431 kB]
Get:19 http://old-releases.ubuntu.com/ubuntu eoan-updates/restricted amd64 Packages [56.6 kB]
Get:20 http://old-releases.ubuntu.com/ubuntu eoan-updates/multiverse i386 Packages [1258 B]
Get:21 http://old-releases.ubuntu.com/ubuntu eoan-updates/universe amd64 Packages [283 kB]
Get:22 http://old-releases.ubuntu.com/ubuntu eoan-updates/main i386 Packages [296 kB]
Get:23 http://old-releases.ubuntu.com/ubuntu eoan-backports/main amd64 Packages [669 B]
Get:24 http://old-releases.ubuntu.com/ubuntu eoan-backports/universe i386 Packages [4106 B]
Get:25 http://old-releases.ubuntu.com/ubuntu eoan-backports/universe amd64 Packages [4108 B]
Get:26 http://old-releases.ubuntu.com/ubuntu eoan-backports/main i386 Packages [669 B]
Get:27 http://old-releases.ubuntu.com/ubuntu eoan-security/universe Sources [33.0 kB]
Get:28 http://old-releases.ubuntu.com/ubuntu eoan-security/universe amd64 Packages [221 kB]
Get:29 http://old-releases.ubuntu.com/ubuntu eoan-security/restricted i386 Packages [7958 B]
Get:30 http://old-releases.ubuntu.com/ubuntu eoan-security/main i386 Packages [195 kB]
Get:31 http://old-releases.ubuntu.com/ubuntu eoan-security/main amd64 Packages [328 kB]
Get:32 http://old-releases.ubuntu.com/ubuntu eoan-security/multiverse amd64 Packages [1074 B]
Get:33 http://old-releases.ubuntu.com/ubuntu eoan-security/restricted amd64 Packages [56.6 kB]
Get:34 http://old-releases.ubuntu.com/ubuntu eoan-security/multiverse i386 Packages [1258 B]
Get:35 http://old-releases.ubuntu.com/ubuntu eoan-security/universe i386 Packages [210 kB]
Fetched 41.3 MB in 8s (4992 kB/s)
Reading package lists... Done

## Installing packages required for setup: lsb-release gnupg...

+ apt-get install -y lsb-release gnupg > /dev/null 2>&1

## Confirming "eoan" is supported...

+ curl -sLf -o /dev/null 'https://deb.nodesource.com/node_14.x/dists/eoan/Release'

## Adding the NodeSource signing key to your keyring...

+ curl -s https://deb.nodesource.com/gpgkey/nodesource.gpg.key | gpg --dearmor | tee /usr/share/keyrings/nodesource.gpg >/dev/null

## Creating apt sources list file for the NodeSource Node.js 14.x repo...

+ echo 'deb [signed-by=/usr/share/keyrings/nodesource.gpg] https://deb.nodesource.com/node_14.x eoan main' > /etc/apt/sources.list.d/nodesource.list
+ echo 'deb-src [signed-by=/usr/share/keyrings/nodesource.gpg] https://deb.nodesource.com/node_14.x eoan main' >> /etc/apt/sources.list.d/nodesource.list

## Running `apt-get update` for you...

+ apt-get update
Hit:1 http://old-releases.ubuntu.com/ubuntu eoan InRelease
Hit:2 http://old-releases.ubuntu.com/ubuntu eoan-updates InRelease
Hit:3 http://old-releases.ubuntu.com/ubuntu eoan-backports InRelease
Hit:4 http://old-releases.ubuntu.com/ubuntu eoan-security InRelease
Get:5 https://deb.nodesource.com/node_14.x eoan InRelease [4582 B]
Get:6 https://deb.nodesource.com/node_14.x eoan/main amd64 Packages [765 B]
Fetched 5347 B in 1s (4127 B/s)
Reading package lists... Done

## Run `sudo apt-get install -y nodejs` to install Node.js 14.x and npm
## You may also need development tools to build native addons:
     sudo apt-get install gcc g++ make
## To install the Yarn package manager, run:
     curl -sL https://dl.yarnpkg.com/debian/pubkey.gpg | gpg --dearmor | sudo tee /usr/share/keyrings/yarnkey.gpg >/dev/null
     echo "deb [signed-by=/usr/share/keyrings/yarnkey.gpg] https://dl.yarnpkg.com/debian stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
     sudo apt-get update && sudo apt-get install yarn
```

**Comment by GirtsR** [comment]
Related to this commit https://github.com/conan-io/conan-docker-tools/commit/b2be5f53e4f4b24667cc322603a1129a3da481b7 maybe? The images run Python version 3.7.5 but the symlink was created for version 3.6.15.

**Comment by uilianries** [comment]
You can use nodejs package instead: https://conan.io/center/nodejs

**Comment by GirtsR** [comment]
@uilianries I cannot, no: I'm depending on specific gcc versions & node in my CI workflows. Switching to a different issue does not really solve the underlying issue in the images that lsb_release is broken.

**Comment by uilianries** [comment]
> Related to this commit [b2be5f5](https://github.com/conan-io/conan-docker-tools/commit/b2be5f53e4f4b24667cc322603a1129a3da481b7) maybe? The images run Python version 3.7.5 but the symlink was created for version 3.6.15.

No, because it only affects docker images like `conanio/gcc9-ubuntu16.04` which are considered "modern". If the docker image which you are using does not have the suffix `-ubuntu16.04` it's not affected.


Anyway, I'll take a look.

**Comment by uilianries** [comment]
A fix should be available as soon as the images are uploaded. Thank you for reporting.

**Comment by GirtsR** [comment]
Latest images are still failing with the issue, unfortunately.

**Comment by uilianries** [comment]
> Latest images are still failing with the issue, unfortunately.

Which conan version? We are releasing 1.44.1 today.

**Comment by GirtsR** [comment]
Looks like 1.44.1 images were released about an hour ago, and for those the issue is fixed (also `:latest` now points to this version). Thanks!

**Comment by uilianries** [comment]
@GirtsR Thank you for your quick answer! Glad that is working now for you!
